---
# tasks file for nginx
- name: Enable amazon-linux-extras epel
  shell: "amazon-linux-extras enable epel"

- name: epel install
  yum:
    name: epel-release
    state: installed

- name: nginx install
  yum:
    name: nginx
    state: latest

- name: start nginx
  service:
    name: nginx
    state: started

- name: Configure Nginx server
  template: src=default.conf dest=/etc/nginx/conf.d/
  notify: restart nginx
