---
# tasks file for mysql
- name: Enable amazon-linux-extras epel
  shell: "amazon-linux-extras enable epel"

- name: epel install
  yum:
    name: "{{ item }}"
    state: installed
  loop:
    - epel-release
    - wget

- name: Add repository
  yum_repository:
    name: mysql
    description: MySql YUM repo
    baseurl: https://dev.mysql.com/downloads/repo/yum/mysql80-community-release-el7-2.noarch.rpm

- name: Install the MySQL packages
  yum:
    name: "{{ item }}"
    state: installed
  loop:
    - mysql-5.6-community-server
    - mysql-5.6-community-client
    - python-mysqldb
    - libmysqlclient-dev

- name: Update MySQL root password for all root accounts
  mysql_user: name=root host="{{ item }}" password="{{ mysql_root_pass }}" state=present
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: Copy the root credentials as .my.cnf file
  template: src=root.cnf.j2 dest=~/.my.cnf mode=0600
