---
# tasks file for mysql
- name: Enable amazon-linux-extras epel
  shell: "amazon-linux-extras enable epel"

- name: epel install
  yum:
    name: "{{ item }}"
    state: installed
  loop:
    - epel-release
    - wget

- name: download remi-mysql repo
  get_url: url=http://dev.mysql.com/get/mysql57-community-release-el7-9.noarch.rpm dest=/tmp/mysql57-community-release-el7-9.noarch.rpm
  tags: mysql

- name: install remi-mysql repo
  shell: /bin/rpm -Uvh /tmp/mysql57-community-release-el7-9.noarch.rpm

- name: install MySQL
  yum: name={{item}} state=present
  with_items:
  - mysql
  - mysql-server
  tags:
  - mysql
  - mysql-service

- name: Update MySQL root password for all root accounts
  mysql_user: name=root host="{{ item }}" password="{{ mysql_root_pass }}" state=present
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: Copy the root credentials as .my.cnf file
  template: src=root.cnf.j2 dest=~/.my.cnf mode=0600
