---
# tasks file for mysql
- name: Enable amazon-linux-extras epel
  shell: "amazon-linux-extras enable epel"

- name: epel install
  yum:
    name: "{{ item }}"
    state: installed
  loop:
    - epel-release
    - wget

- name: Get repo
  get_url:
    url: https://dev.mysql.com/get/mysql57-community-release-el7-11.noarch.rpm

- name: Install repo
  shell: rpm -ivh mysql57-community-release-el7-11.noarch.rpm

- name: Install the MySQL packages
  yum:
    name: "{{ item }}"
    state: installed
  loop:
    - mysql-server
    - MySQL-python

- name: Start MySQL
  service:
    name: mysqld
    state: started
    enabled: yes
