---
# tasks file for tomcat
- name: Enable amazon-linux-extras epel
  shell: "amazon-linux-extras enable epel"

- name: java install
  yum:
    name: java-1.8.0-openjdk
    state: present

- name: add group "tomcat"
  group: name=tomcat

- name: add user "tomcat"
  user: name=tomcat group=tomcat home=/usr/share/tomcat createhome=no
  become: True
  become_method: sudo

- name: Creates tomcat directory
  file:
    path: /opt/tomcat
    state: directory
    owner: tomcat
    group: tomcat
    recurse: yes

- name: Unarchive a file with extra options
  unarchive:
    src: http://www-us.apache.org/dist/tomcat/tomcat-8/v8.5.38/bin/apache-tomcat-8.5.38.tar.gz
    dest: /opt/tomcat
    remote_src: yes
    extra_opts:
    - --strip-components=1

- name: Symlink install directory
  file: src=/opt/tomcat path=/usr/share/tomcat state=link

- name: Change ownership of Tomcat installation
  file: path=/usr/share/tomcat/ owner=tomcat group=tomcat state=directory recurse=yes

- name: Configure Tomcat server
  template: src=server.xml dest=/usr/share/tomcat/conf/
  notify: restart tomcat

- name: Configure Tomcat users
  template: src=tomcat-users.xml dest=/usr/share/tomcat/conf/
  notify: restart tomcat

- name: Configure Tomcat users access
  template: src=context.xml dest=/opt/tomcat/webapps/manager/META-INF/
  notify: restart tomcat

- name: Install Tomcat init script
  copy: src=tomcat-initscript.sh dest=/etc/init.d/tomcat mode=0755

- name: Setup a Systemd unit file for Apache Tomcat
  copy: src=tomcat.service dest=/etc/systemd/system/

- name: Start Tomcat
  service: name=tomcat state=started enabled=yes
